/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "eeprom.h"
#include<string.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	EEPROM_Init();
	int ch;
	char str[32];
	UartInit(BAUD_9600);
	UartGets(str);

do{
	UartPuts("Enter your choice \r n");
	UartPuts("write string \r\n");
	UartPuts("read string \r\n");
	//UartGets(str);
	sscanf(str, "%d", &ch);

	switch(ch)
	{
	case 1:
		UartGets(str);
		EEPROM_Write(0x0020,(uint8_t *) str,16);
		break;
	case 2:
		EEPROM_Read(0x0020,(uint8_t*)str,16);
		UartPuts(str);
		break;
	}

}while(ch !=0);
	return 0;
}
