/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "i2c.h"
#include "i2c_lcd.h"
#include "adc.h"
//#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int count;
	char str[32];
	uint16_t val;
	SystemInit();
	ADC_Init();
	LcdInit();
	while(1) {
		val = ADC_GetValue();
		sprintf(str, "ADC=%d", val);
		LcdPuts(LCD_LINE1,str);
		for(count = 0; count < 4096; count++)
		sprintf(str, "ADC=%d", val);
		LcdPuts(LCD_LINE2,str);
		DelayMs(1000);

	}
	return 0;
}
































/*
  stm32 + uart + ldr
  PA2  - rx
  PA3 - tx
  gnd - gnd
  LDR:PA0,vdd

 */
