/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "i2c.h"
#include "i2c_lcd.h"
#include "uart.h"
#include "spi.h"
#include "lis3dsh.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	int ret;
	LIS_Data val;
	LcdInit();
	SystemInit();
	UartInit(BAUD_9600);
	UartPuts("LIS3DSH Accel Demo!\r\n");

	LcdPuts(LCD_LINE1, "ORIENTATION");
	LIS_Init();
	DelayMs(1000);
	while(1) {
		ret = LIS_DRdy();
		if(ret) {
			val = LIS_GetData();
			sprintf(str, "x%d y%d z%d\r\n", val.x, val.y, val.z);
			LcdPuts(LCD_LINE2, str);
			UartPuts("ORIENTATION \t");
			UartPuts(str);
			DelayMs(1000);
		}
	}
	return 0;
}







