/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)

{

	//char str[4];

	char ch = 0 ;

	SystemInit();

	LedInit(LED_GREEN);

	LedInit(LED_BLUE);

	LedInit(LED_RED);

	LedInit(LED_ORANGE);

	UartInit(BAUD_9600);

	//UartPuts("Enter Strings...\r\n");

	while(1) {

		//UartGets(str);

		//strupr(str);


		UartPuts("Enter your choice \r\n1.LED blue\r\n2.LED red\r\n3.LED Orange\r\n4.LED Green\r\n");

		ch = UartGetch();

        switch(ch)

        {

           case '1':

        	     LedBlink(LED_GREEN, 1000);

        	     break;

           case '2':

        	     LedBlink(LED_BLUE, 1000);

        	     break;

           case '3':

        	     LedBlink(LED_RED, 1000);

        	     break;

           case '4':

        	     LedBlink(LED_ORANGE, 1000);

        	     break;

        }

        ch = 0;

	}

	return 0;

}
